/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSwipeRouteImport } from './routes/_authenticated/swipe'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaywallRouteImport } from './routes/_authenticated/paywall'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPropertyNewRouteImport } from './routes/_authenticated/property.new'
import { Route as AuthenticatedChatMatchIdRouteImport } from './routes/_authenticated/chat.$matchId'
import { Route as AuthenticatedAdminPropertiesRouteImport } from './routes/_authenticated/admin.properties'
import { Route as ApiPublicWebhooksRevenuecatRouteImport } from './routes/api/public/webhooks/revenuecat'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSwipeRoute = AuthenticatedSwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaywallRoute = AuthenticatedPaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertyNewRoute =
  AuthenticatedPropertyNewRouteImport.update({
    id: '/property/new',
    path: '/property/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatMatchIdRoute =
  AuthenticatedChatMatchIdRouteImport.update({
    id: '/chat/$matchId',
    path: '/chat/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPropertiesRoute =
  AuthenticatedAdminPropertiesRouteImport.update({
    id: '/admin/properties',
    path: '/admin/properties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksRevenuecatRoute =
  ApiPublicWebhooksRevenuecatRouteImport.update({
    id: '/api/public/webhooks/revenuecat',
    path: '/api/public/webhooks/revenuecat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/paywall': typeof AuthenticatedPaywallRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/swipe': typeof AuthenticatedSwipeRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/property/new': typeof AuthenticatedPropertyNewRoute
  '/api/public/webhooks/revenuecat': typeof ApiPublicWebhooksRevenuecatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/paywall': typeof AuthenticatedPaywallRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/swipe': typeof AuthenticatedSwipeRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/property/new': typeof AuthenticatedPropertyNewRoute
  '/api/public/webhooks/revenuecat': typeof ApiPublicWebhooksRevenuecatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/paywall': typeof AuthenticatedPaywallRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/swipe': typeof AuthenticatedSwipeRoute
  '/_authenticated/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/_authenticated/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/_authenticated/property/new': typeof AuthenticatedPropertyNewRoute
  '/api/public/webhooks/revenuecat': typeof ApiPublicWebhooksRevenuecatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/home'
    | '/inbox'
    | '/matches'
    | '/notifications'
    | '/onboarding'
    | '/paywall'
    | '/profile'
    | '/search'
    | '/swipe'
    | '/admin/properties'
    | '/chat/$matchId'
    | '/property/new'
    | '/api/public/webhooks/revenuecat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/home'
    | '/inbox'
    | '/matches'
    | '/notifications'
    | '/onboarding'
    | '/paywall'
    | '/profile'
    | '/search'
    | '/swipe'
    | '/admin/properties'
    | '/chat/$matchId'
    | '/property/new'
    | '/api/public/webhooks/revenuecat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/home'
    | '/_authenticated/inbox'
    | '/_authenticated/matches'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/paywall'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/swipe'
    | '/_authenticated/admin/properties'
    | '/_authenticated/chat/$matchId'
    | '/_authenticated/property/new'
    | '/api/public/webhooks/revenuecat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicWebhooksRevenuecatRoute: typeof ApiPublicWebhooksRevenuecatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/swipe': {
      id: '/_authenticated/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof AuthenticatedSwipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paywall': {
      id: '/_authenticated/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof AuthenticatedPaywallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/property/new': {
      id: '/_authenticated/property/new'
      path: '/property/new'
      fullPath: '/property/new'
      preLoaderRoute: typeof AuthenticatedPropertyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$matchId': {
      id: '/_authenticated/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof AuthenticatedChatMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/properties': {
      id: '/_authenticated/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/revenuecat': {
      id: '/api/public/webhooks/revenuecat'
      path: '/api/public/webhooks/revenuecat'
      fullPath: '/api/public/webhooks/revenuecat'
      preLoaderRoute: typeof ApiPublicWebhooksRevenuecatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPaywallRoute: typeof AuthenticatedPaywallRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSwipeRoute: typeof AuthenticatedSwipeRoute
  AuthenticatedAdminPropertiesRoute: typeof AuthenticatedAdminPropertiesRoute
  AuthenticatedChatMatchIdRoute: typeof AuthenticatedChatMatchIdRoute
  AuthenticatedPropertyNewRoute: typeof AuthenticatedPropertyNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPaywallRoute: AuthenticatedPaywallRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSwipeRoute: AuthenticatedSwipeRoute,
  AuthenticatedAdminPropertiesRoute: AuthenticatedAdminPropertiesRoute,
  AuthenticatedChatMatchIdRoute: AuthenticatedChatMatchIdRoute,
  AuthenticatedPropertyNewRoute: AuthenticatedPropertyNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicWebhooksRevenuecatRoute: ApiPublicWebhooksRevenuecatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
